Fix: Section SetPoint Layout Bug
AdiAddons/AdiBags pull request #721
Opened 2022-10-22 23:49 UTC by CodeAnxiety

This corrects the `SetPoint failed` issue, which can happen intermittently by resetting the `SetPoint` of each section at the beginning of the layout.

As best I can tell, this is caused by the sort order changing between layouts, which can cause occasionally cause any number of sections to form a circular dependency.

Addresses #551

2022-10-24 18:09 UTC, Cidan requested changes
Take a look at my comment below. Thanks for the CL!

2022-10-24 18:09 UTC, Cidan commented on widgets/ContainerFrame.lua
> +	for key, section in pairs(sections) do section:SetPoint("TOPLEFT") end
I wonder if we should do a ClearAllPoints() here instead, to ensure all points are reset, and not just the topleft.

2022-12-02 23:22 UTC, mwazelinski commented
Hi, I was hitting this bug trying to implement a simple section reordering plugin. It seems that this condition causes it:
```
if numRows > 1 then
    section:SetPoint('TOPLEFT', rows[numRows-1], 'BOTTOMLEFT', 0, -ROW_SPACING)
end
```
I removed it and after a very quick test I didn't have any issues. @Cidan could you explain what is the purpose of this condition?

2022-12-05 04:30 UTC, CodeAnxiety commented
Are asking me?

I believe that block is connecting the current section (`rows[numRows]`) to the previous section (`rows[numRows - 1]`).

If you're hitting the bug there it may mean that the section you're updating (via `SetPoint`) is trying to link to another section that's already linked to it, creating a circular dependency.

This PR attempts to fix that by clearing all the points at the beginning of the layout so there can be no pre-existing links between sections.

For example:
  First layout:
     Order: A, B, C
     Links: A <- B <- C
  Second layout:
    Order: C, A, B
    Links: C <- A <- B 

If you don't clear the points first, then the second layout will fail when linking A with C will because C still links with B which links A, and A cannot be linked to itself.  I.e you thought you were doing `C <- A`, but you were actually doing `A <- B <- C <- A`.

2023-02-08 09:47 UTC, closed without merging